DDCE-4696: Changes as part of config warnings
hmrc/ers-checking-frontend pull request #142
Opened 2023-10-10 11:50 UTC by PaulC-TDS

2023-10-11 07:20 UTC, PaulC-TDS commented
Bobby warning from PR bot 
```
[warn] WARNING: Your build has 1 bobby warning(s). Please take action to fix these before the listed date, or they will become violations that fail your build
[warn]  (1) uk.gov.hmrc:http-caching-client (10.0.0-play-28)
```
This will be fixed by [DDCE-4689](https://jira.tools.tax.service.gov.uk/browse/DDCE-4689)

2023-10-11 11:01 UTC, slavvco requested changes

2023-10-11 11:01 UTC, slavvco commented on conf/application.conf
> +    protocol = https
change as discussed

2023-10-12 07:40 UTC, slavvco approved these changes

2023-10-16 09:54 UTC, merged