Ddce 4689 2
hmrc/ers-checking-frontend pull request #145
Opened 2023-12-08 15:12 UTC by MRBeresford

# DDCE-???

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist PR Raiser
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  I've squashed my commits - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2023-12-18 13:55 UTC, matthewwardcap requested changes
Looks all good, one very minor change

2023-12-18 14:20 UTC, matthewwardcap commented on app/utils/ERSUtil.scala
> +class ERSUtil @Inject()()
In fact believe it can just be replaced with `class ERSUtil` since nothing is being injected any more

2023-12-18 17:49 UTC, MRBeresford commented on app/utils/ERSUtil.scala
> +class ERSUtil @Inject()()
Good spot, replaced with just `class ERSUtil`

2023-12-19 10:17 UTC, matthewwardcap approved these changes

2023-12-20 09:01 UTC, merged